server:
  port: 8761  #eureka端口

spring:
  application:
    name: eureka-server  #微服务名称

eureka:
  #server的配置
  server:
    eviction-interval-timer-in-ms: 10000  #eviction:驱除----服务端间隔多少毫秒做定期删除的操作，默认30S
    renewal-percent-threshold: 0.85  #threshold:临界点---超过0.85的应用都没有建立联系，就不会剔除服务

  #实例的配置
  instance:
    #实例的id包括三部分【主机名:微服务名称:ip】
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
    hostname: localhost  #主机名称
    prefer-ip-address: true  #以ip的形式显示信息
    lease-renewal-interval-in-seconds: 5  #服务的续约时间，时间是秒【默认是30S】


  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost/eureka}
    register-with-eureka: ${REGISTER_WITH_EUREKA:true}
    fetch-registry: true