server:
  port: 2222  #端口

spring:
  application:
    name: eureka-client-two  #微服务名称

eureka:
  #客户端配置
  client:
    service-url:
      defaultZone: http://peer1 :8761/eureka  #注册中心地址
    register-with-eureka: true  #是否注册到eureka
    fetch-registry: true  #是否拉取服务列表到本地
    registry-fetch-interval-seconds: 5   #为了缓解服务列表脏读问题，多久拉取一次【时间是S】

  #实例的配置
  instance:
    #实例的id包括三部分【主机名:微服务名称:ip】
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
    hostname: localhost  #主机名称
    prefer-ip-address: true  #以ip的形式显示信息
    lease-renewal-interval-in-seconds: 5  #服务的续约时间，时间是秒【默认是30S】