server:
  port: 80

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      enabled: true  #开启gateway
      routes:
        - id: login-service-route
          uri: http://localhost:8081
          predicates: #断言匹配，断言是给路由使用的
            - Path=/doLogin #和服务中的路径匹配,是正则匹配的模式
            - After=2022-06-27T16:48:29.089+08:00[Asia/Shanghai]  #在时间之后才能访问
            - Method=GET,POST  #指定请求方式
            - Query=name  #必须传入参数name
          filters:
            - name: RequestRateLimiter  #过滤器名称，固定
              args:
                key-resolver: '#{@ipLimit}' #使用哪种限流策略
                redis-rate-limiter.replenishRate: 1  #生成令牌速度
                redis-rate-limiter.burstCapacity: 3  #生成令牌桶大小
      discovery:
        locator:
          enabled: true   #开启动态路由
          lower-case-service-id: true  #开启小写字母，eureka默认是大写微服务名称
  redis:
    host: 192.168.220.148

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    registry-fetch-interval-seconds: 3  #拉取服务列表的时间，对于gateway来说短一点好点，默认30S

  instance:
    hostname: localhost
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}